name: cd

on:
  push:

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Enable tmate debug"
        type: boolean
        default: "false"

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    uses: octue/workflows/.github/workflows/deploy-cloud-run-service.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      gcp_project_name: octue-sdk-python
      gcp_project_number: 437801218871
      gcp_region: europe-west1
      gcp_resource_affix: octue
      gcp_service_name: example-service-cloud-run
      cloud_run_flags: "--ingress=all --allow-unauthenticated"
      local_dockerfile: ./Dockerfile
